name: ExphcTweaks
main: me.exphc.ExphcTweaks.ExphcTweaks
version: 1.2.5rev5c
commands:
    clear:
        description: Clear nearby item drops
        usage: /clear [player]|all
    loadchunk:
        description: Load a chunk
        usage: /loadchunk world x z
    chunk:
        description: Resend your chunk
        usage: /chunk
    breakballoon:
        description: Break your hot air balloon into an item
        usage: /breakballoon
        aliases:
        - breakb
        - break
        - bb
    dropnether:
        description: Drop below bedrock in The Nether
        usage: /dropnether
    tell:
        description: Do not tell
        usage: /tell
softdepend:
    - RecipeRepo
