name: ExphcTweaks
main: me.exphc.ExphcTweaks.ExphcTweaks
version: 1.2.5
commands:
    clear:
        description: Clear nearby item drops
        usage: /clear [player]|all
    loadchunk:
        description: Load a chunk
        usage: /loadchunk world x z
    chunk:
        description: Resend your chunk
        usage: /chunk
    breakballoon:
        description: Break your hot air balloon into an item
        usage: /breakballoon
        aliases:
        - breakb
        - break
        - bb
softdepend:
    - RecipeRepo
