name: ExphcTweaks
main: me.exphc.ExphcTweaks.ExphcTweaks
version: 1.1
commands:
    chunk:
        description: Resend your chunk
        usage: /chunk
softdepend: [RecipeRepo] # so it removes recipes first, before we add our own
