name: BugTest1
main: me.exphc.BugTest1.BugTest1
version: 0
commands:
    chunk:
        description: Resend your chunk
        usage: /chunk
softdepend: [RecipeRepo] # so it removes recipes first, before we add our own
